In [2]:
import numpy as np

a = np.random.randn(5)
print(a)

[-0.09067628 -0.0731129   1.27117941 -0.84054288  0.37639235]


In [3]:
print(a.shape)
# Rank 1 array
# Neither a row vector nor a column vector

(5,)


In [5]:
print(a.T)
# Will look the same

[-0.09067628 -0.0731129   1.27117941 -0.84054288  0.37639235]


In [6]:
print(np.dot(a, a.T))
# will give back a single number

2.4776482944939966


In [8]:
# Instead, create a 5x1 vector to avoid the confusion
a = np.random.randn(5,1) # column vector
print(a)

[[-1.10670872]
 [-1.22738246]
 [-0.14127143]
 [-1.53315823]
 [-1.65869339]]


In [9]:
print(a.T)

[[-1.10670872 -1.22738246 -0.14127143 -1.53315823 -1.65869339]]


In [10]:
print(np.dot(a,a.T))

[[1.22480418 1.35835486 0.15634632 1.69675957 1.83569043]
 [1.35835486 1.5064677  0.17339408 1.88177151 2.03585117]
 [0.15634632 0.17339408 0.01995762 0.21659146 0.23432599]
 [1.69675957 1.88177151 0.21659146 2.35057415 2.54303942]
 [1.83569043 2.03585117 0.23432599 2.54303942 2.75126376]]
